import { ToolProvider } from '../interfaces/index.js';
import { ToolResponse } from './response.js';
import {
  DeleteRepositorySpec,
  LocalRepoSpec,
  RepositorySpec,
} from './schema.js';
import { GitHubClient } from '../utils/index.js';

interface CreateRepositoryOutput {
  repositoryUrl: string;
}

const DEFAULT_COMMIT_MESSAGE =
  'feat: initial commit generated by scaffolder AI';

export abstract class GithubTool<T> extends ToolProvider<T> {
  constructor(private readonly client: GitHubClient) {
    super();
  }

  async createRepository(
    spec: RepositorySpec,
  ): Promise<ToolResponse<CreateRepositoryOutput>> {
    try {
      const { name, description, visibility, hasIssues, hasProjects, hasWiki } =
        spec;
      const repositoryUrl = await this.client.createRepository({
        name,
        description,
        visibility,
        hasIssues,
        hasProjects,
        hasWiki,
      });

      return {
        body: { repositoryUrl },
        status: 'success',
      };
    } catch (error) {
      this.handleError(
        error,
        `Failed to create GitHub repository: ${spec.name}`,
        'createRepository',
      );
    }
  }

  async addRemoteOrigin({
    localPath,
    repositoryUrl,
  }: LocalRepoSpec): Promise<ToolResponse<void>> {
    try {
      await this.client.addremote(localPath, repositoryUrl);
      return { status: 'success' };
    } catch (error) {
      this.handleError(
        error,
        `Failed to add remote origin: ${repositoryUrl} to local path: ${localPath}`,
        'addRemoteOrigin',
      );
    }
  }

  async checkinFiles({
    localPath,
    message,
  }: LocalRepoSpec): Promise<ToolResponse<void>> {
    try {
      await this.client.commitAndPush(
        localPath,
        message ?? DEFAULT_COMMIT_MESSAGE,
      );
      return { status: 'success' };
    } catch (error) {
      this.handleError(
        error,
        `Failed to commit and push files: localPath=${localPath}, message=${message}`,
        'checkinFiles',
      );
    }
  }

  async deleteRepository({
    owner,
    name,
  }: DeleteRepositorySpec): Promise<ToolResponse<void>> {
    try {
      await this.client.deleteRepository(name, owner);
      return { status: 'success' };
    } catch (error) {
      this.handleError(
        error,
        `Failed to delete GitHub repository: ${owner}/${name}`,
        'deleteRepository',
      );
    }
  }
}
